# Generated by Django 5.1.1 on 2024-12-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address1', models.CharField(max_length=200)),
                ('adress2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('fast_delivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='assortment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='polls.assortment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='polls.order')),
            ],
        ),
    ]
