# Generated by Django 5.1.1 on 2024-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
