# Generated by Django 5.1.1 on 2024-12-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_assortment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress2',
            new_name='address2',
        ),
    ]
