# Generated by Django 5.1.1 on 2024-12-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_adress2_order_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='type',
            field=models.CharField(choices=[('COFFEE', 'Coffee'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], default='COFFEE', max_length=20),
        ),
    ]
